### ISSUE TITLE
side does not load

### ISSUE THREAD

**Issue by mitulp236** [100mslive/100ms-web-v1#45]
![Screenshot from 2021-06-01 17-48-00](https://user-images.githubusercontent.com/28555455/120322081-a543ce00-c301-11eb-93da-667558fdf438.png)
![Screenshot from 2021-06-01 17-47-55](https://user-images.githubusercontent.com/28555455/120322087-a674fb00-c301-11eb-9e64-d2879f78c1bf.png)

**Comment by pratikshadake** [comment]
Hey @mitulp236 we've sent you slack invite to your email id - testyemailid@gmail.com (with which you have registered) Request you to accept the invite for resolving this issue.

**Comment by mitulp236** [comment]
ok, Thank you
